/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(${name}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary:                    v('--primary'),
        'on-primary':               v('--on-primary'),
        'primary-container':        v('--primary-container'),
        secondary:                  v('--secondary'),
        'secondary-container':      v('--secondary-container'),
        'on-secondary-container':   v('--on-secondary-container'),
        tertiary:                   v('--tertiary'),
        'tertiary-fixed':           v('--tertiary-fixed'),
        error:                      v('--error'),
        'on-error':                 v('--on-error'),
        'error-container':          v('--error-container'),
        surface:                    v('--surface'),
        'surface-bright':           v('--surface-bright'),
        'surface-container-lowest': v('--surface-container-lowest'),
        'surface-container-low':    v('--surface-container-low'),
        'surface-container':        v('--surface-container'),
        'surface-container-high':   v('--surface-container-high'),
        'surface-container-highest':v('--surface-container-highest'),
        'surface-variant':          v('--surface-variant'),
        'on-surface':               v('--on-surface'),
        'on-surface-variant':       v('--on-surface-variant'),
        outline:                    v('--outline'),
        'outline-variant':          v('--outline-variant'),
        background:                 v('--background'),
        'on-background':            v('--on-surface'),
        'sidebar-bg':               v('--sidebar-bg'),
        violet:                     v('--violet'),
        amber:                      v('--amber'),
        /* semantic aliases — mirrors component token names */
        'primary-fg':               v('--on-primary'),
        'primary-soft':             v('--primary-container'),
        'surface-muted':            v('--surface-container-low'),
        'surface-low':              v('--surface-container-low'),
        'surface-overlay':          v('--surface-variant'),
        text:                       v('--on-surface'),
        'text-muted':               v('--on-surface-variant'),
        'text-subtle':              v('--outline'),
        border:                     v('--outline-variant'),
        'border-strong':            v('--outline'),
        danger:                     v('--error'),
        'danger-bg':                v('--error-container'),
        success:                    v('--success'),
        'success-bg':               v('--success-container'),
        warning:                    v('--warning'),
        'warning-bg':               v('--warning-container'),
        info:                       v('--info'),
        'info-bg':                  v('--info-container'),
      },
      borderRadius: {
        'xs': '0.25rem',
      },
      spacing: {
        gutter:           '24px',
        'margin-desktop': '32px',
        'margin-mobile':  '16px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans:    ['Geist', 'sans-serif'],
        display: ['"Bricolage Grotesque"', 'Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['32px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-base':   ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
